routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('master');
});

Route::get('/blog', 'BlogController@blogAll');

Route::get('/', 'IndexController@index');

Route::get('post/{id}', 'IndexController@showBlog');

Route::post('/depoimento/create', 'IndexController@TestimonialStore');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/send', 'EmailController@send');

Route::get('/blog/exclusivo/{id}', 'HomeController@blog');

Route::resource('comentario', 'UserCommentController');

Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {

    Route::get('/', 'IndexController@Dashboardindex');
    Route::resource('comentarios', 'CommentController');
    Route::resource('image', 'ImageController');
    Route::resource('newsletter', 'NewsController');
    Route::resource('parceria', 'PartnerController');
    Route::resource('post', 'PostController');
    Route::resource('preco', 'PriceController');
    Route::resource('depoimentos', 'TestimonialController');
    Route::resource('alunos', 'StudentController');

    Route::get('downloadNewsletter', 'AdminController@downloadNewsletter');
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = [
        'title', 'comment', 'post_id', 'user_id',
    ];

    public function post()
    {
        return $this->belongsTo('App\Post');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\User;
use Auth;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $comments = Comment::all();

        return view('admin.comentarios.index')->with('comments', $comments);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.comentarios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::find(Auth::user()->id);

        if(!empty($user)) {
            $comment = new Testimonial(['text' => $request->input('text'),
                'name' => $request->input('name'),
                'approved' => 0]);

            $user->comentarioss()->save($comment);
        } else {
            $comment = new Testimonial;

            $comment->text = $request->input('text');
            $comment->name = $request->input('name');
            $comment->approved = 0;

            $comment->save();
        }

        /*
        return view('admin.comentarios.show')->with('success', trans('comentarios.create-message_success'))
            ->with('comments', $comment);
        */

        return redirect()->back()->with('success', 'Depoimento criado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('admin.comentarios.show')->with('comments', Comment::find($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.comentarios.edit')->with('comments', Comment::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $comment = Comment::find($id);

        $text = $request->input('text');
        $name = $request->input('name');
        $input = $request->input('approved');

        $comment->text = isset($text) ? $text : $comment->text;
        $comment->name = isset($name) ? $name : $comment->name;
        $comment->approved = isset($input) ? $input : $comment->approved;

        $comment->save();

        //return redirect('admin/comentarios')->with('success', 'Depoimento foi alterado!');

        return redirect('admin/comentarios')->with('success', 'Depoimento #' . $comment->id . ' foi alterado!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $comment = Comment::find($id);
        $comment->delete();

        return redirect('admin/comentarios')->with('success', 'Depoimento deletada!');
    }
}

resources/views/admin/comments/create.blade.php
@extends('admin.master')

@section('title', trans('comment.title-create'))
@section('subtitle', trans('comment.subtitle-create'))
@section('breadcrumb', Breadcrumbs::render('comment_create'))

@section('content')
    <div class="col-lg-12">

        {!! BootForm::open()->action(route('comentarios.store'))->multipart() !!}

        {!! BootForm::textarea(trans('comment.form-text'), 'text')->rows(5)->required() !!}
        {!! BootForm::text('Nome', 'name')->placeholder('Insira o nome completo')->helpblock('Esse nome será mostrado como o nome da pessoa que fez o depoimento')->required() !!}
        @include('admin.comments.button.cancel')
        {!! BootForm::submit(trans('comment.form-btn-submit'))->addclass('btn btn-primary') !!}

        {!! BootForm::close() !!}

    </div>
@endsection

resources/views/admin/comments/edit.blade.php
@extends('admin.master')

@section('title', trans('comment.title-edit'))
@section('subtitle', trans('comment.subtitle-edit'))
@section('breadcrumb', Breadcrumbs::render('comment_edit', $comment))

@section('content')
    <div class="col-lg-12">

        {!! BootForm::open()->action( route('comentarios.update', $comment->id) )->put() !!}
        {!! BootForm::bind($comment) !!}

        {!! BootForm::textarea(trans('comment.form-edit_text'), 'text')->rows(5)->required() !!}
        {{-- BootForm::text(trans('comment.form-edit_text'), 'name')->required() --}}
        <label>Nome</label>
        <input name='name' type="text" value="{{ $comment->name or $comment->user->name }}" class="form-control" placeholder="{{ trans('comment.form-name-placeholder') }}" required>
        <br>

        @include('admin.comments.button.cancel')
        {!! BootForm::submit(trans('comment.button-edit'))->addClass('btn btn-primary') !!}

        {!! BootForm::close() !!}

        <br>
        @include('admin.comments.button.delete')

    </div>
@endsection

resources/views/admin/comments/index.blade.php
@extends('admin.master')

@section('title', trans('comment.title-index'))
@section('subtitle', trans('comment.subtitle-index'))
@section('breadcrumb', Breadcrumbs::render('comment'))

@section('content')

    @if( !isset($comments) )
        <div class="alert alert-info" role="alert">
            <strong>Ops!</strong> Parece que você não tem nenhum testimonialagem cadastrada ainda <a href="testimonial/create" class="alert-link">clique aqui</a> para criar uma nova.
        </div>
    @endif

    <div class="col-md-12">
        <p> @include('admin.comments.button.create') </p>
    </div>

    @foreach($comments as $comment)
        <div class="ro">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="thumbnail">

                    <div class="caption">
                        <h4> Depoimento {{ $comment->id }} - @include('admin.comments.components.label') </h4>
                        <h5> Criado por <strong>{{ $comment->name or $comment->user->name }}</strong> as {{ $comment->created_at }}</h5>
                        <p> {{ $comment->text}} </p>

                        <div class="custom-form">

                            {!! BootForm::open()->action( route('comentarios.update', $comment->id) )->put() !!}
                            <input type="hidden" name="approved" value="1">

                            <button type="submit" class="btn btn-large btn-success btn-custom">
                                <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Aprovar
                            </button>

                            {!! BootForm::close() !!}

                            {!! BootForm::open()->action( route('comentarios.update', $comment->id) )->put() !!}
                            <input type="hidden" name="approved" value="2">

                            <button type="submit" class="btn btn-large btn-danger btn-custom">
                                <i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Rejeitar
                            </button>

                            {!! BootForm::close() !!}

                            @include('admin.comments.button.edit')

                        </div>

                    </div>
                </div>
            </div>
        </div>

    @endforeach

@endsection

resources/views/admin/comments/show.blade.php
@extends('admin.master')

@section('title', trans('comment.title-show'))
@section('subtitle', trans('comment.subtitle-show'))
@section('breadcrumb', Breadcrumbs::render('comment_show', $comment))

@section('content')
    <div class="row">
        <div class="col-md-12">

            @include('components.alert')

            <div class="col-xs-12 col-sm-4 col-md-6 col-lg-6">
                <span class="thumbnail">
                    <img src="{{ asset( $comment->image_url) }}" alt="...">
                </span>
            </div>

            <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">
                <h2> {{ $comment->title }} </h2>
                <h4> {{ $comment->subtitle }}</h4>
                {!! $comment->text !!}
            </div>

        </div>

        <div class="col-md-12">

            <a class="btn btn-small btn-default" href="{{ URL::to('admin/post/') }}"> @lang('testimonial.button-back') </a>

            @include('admin.comments.button.edit')

            @include('admin.comments.button.delete')
        </div>
    </div>
@endsection