routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('master');
});

Route::get('/blog', 'BlogController@blogAll');

Route::get('/', 'IndexController@index');

Route::get('post/{id}', 'IndexController@showBlog');

Route::post('/depoimento/create', 'IndexController@TestimonialStore');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/send', 'EmailController@send');

Route::get('/blog/exclusivo/{id}', 'HomeController@blog');

Route::resource('comentario', 'UserCommentController');

Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {

    Route::get('/', 'IndexController@Dashboardindex');
    Route::resource('comentarios', 'CommentController');
    Route::resource('image', 'ImageController');
    Route::resource('newsletter', 'NewsController');
    Route::resource('parceria', 'PartnerController');
    Route::resource('post', 'PostController');
    Route::resource('preco', 'PriceController');
    Route::resource('depoimentos', 'TestimonialController');
    Route::resource('alunos', 'StudentController');

    Route::get('downloadNewsletter', 'AdminController@downloadNewsletter');
});

resources/views/admin/include/breadcrumb.blade.php
<li class="active">
    <i class="fa fa-dashboard"></i> asd
</li>

resources/views/admin/include/css.blade.php
<!-- Bootstrap Core CSS -->
<link href=" https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css " rel="stylesheet">

<!-- Custom CSS -->
<link href=" {{ asset('css/sb-admin.css') }} " rel="stylesheet">

<!-- Morris Charts CSS -->
<link href=" {{ asset('css/plugins/morris.css') }} " rel="stylesheet">

<!-- Custom Fonts -->
<link href=" {{ asset('css/font-awesome.min.css') }} " rel="stylesheet" type="text/css">

<link href=" {{ asset('css/custom.css') }} " rel="stylesheet" type="text/css">

resources/views/admin/include/js.blade.php
<!-- jQuery -->
<script src=" {{ asset('js/jquery.js') }} "></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src=" {{ asset('js/bootstrap.min.js') }} "></script>

<!-- Morris Charts JavaScript -->
<script src=" {{ asset('js/plugins/morris/raphael.min.js') }} "></script>
<script src=" {{ asset('js/plugins/morris/morris.min.js') }} "></script>
<script src=" {{ asset('js/plugins/morris/morris-data.js') }} "></script>

resources/views/admin/include/navbar.blade.php
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ url('admin') }}"> @lang('client.name') </a>
    </div>
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ Auth::user()->name }} <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                </li>
            </ul>
        </li>
    </ul>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            <li class="{{ Request::is('admin') ? 'active' : '' }}">
                <a href="{{ action('IndexController@Dashboardindex') }}"><i class="fa fa-fw fa-dashboard"></i> @lang('admin.nav_dashboard') </a>
            </li>
            <li class="{{ Request::is('admin/preco') ? 'active' : '' }}">
                <a href="{{ route("preco.index") }}"><i class="fa fa-fw fa-money"></i> @lang('admin.nav_prices') </a>
            </li>
            <li class="{{ Request::is('admin/post') ? 'active' : '' }}">
                <a href="{{ route("post.index") }}"><i class="fa fa-fw fa-newspaper-o"></i> @lang('admin.nav_posts') </a>
            </li>
            <li class="{{ Request::is('admin/depoimentos') ? 'active' : '' }}">
                <a href="{{ route("depoimentos.index") }}"><i class="fa fa-fw fa-bullhorn"></i> @lang('admin.nav_testimonials') </a>
            </li>
            <li class="{{ Request::is('admin/parceria') ? 'active' : '' }}">
                <a href="{{ route("parceria.index") }}"><i class="fa fa-fw fa-user-plus"></i> @lang('admin.nav_partners') </a>
            </li>
            <li class="{{ Request::is('admin/alunos') ? 'active' : '' }}">
                <a href="{{ route("alunos.index") }}"><i class="fa fa-fw fa-group"></i> @lang('admin.nav_students') </a>
            </li>
            <li>
                <a href="{{ url('admin/downloadNewsletter') }}"><i class="fa fa-fw fa-rss"></i> @lang('admin.nav_news') </a>
            </li>

            <!--
            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="demo" class="collapse">
                    <li>
                        <a href="#">Dropdown Item</a>
                    </li>
                    <li>
                        <a href="#">Dropdown Item</a>
                    </li>
                </ul>
            </li>
            -->
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>