routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('master');
});

Route::get('/blog', 'BlogController@blogAll');

Route::get('/', 'IndexController@index');

Route::get('post/{id}', 'IndexController@showBlog');

Route::post('/depoimento/create', 'IndexController@TestimonialStore');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/send', 'EmailController@send');

Route::get('/blog/exclusivo/{id}', 'HomeController@blog');

Route::resource('comentario', 'UserCommentController');

Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {

    Route::get('/', 'IndexController@Dashboardindex');
    Route::resource('comentarios', 'CommentController');
    Route::resource('image', 'ImageController');
    Route::resource('newsletter', 'NewsController');
    Route::resource('parceria', 'PartnerController');
    Route::resource('post', 'PostController');
    Route::resource('preco', 'PriceController');
    Route::resource('depoimentos', 'TestimonialController');
    Route::resource('alunos', 'StudentController');

    Route::get('downloadNewsletter', 'AdminController@downloadNewsletter');
});

resources/views/parts/blog_post.blade.php
<div class="col-md-4">
    <article class="">
        <div class="">
            <img class="blog-img" src="{{ asset( $post->image_url ) }}" alt="image">
        </div>
        <div class="col-md-12">
            <small>
                <div class="blog-post">
                    <h6> {{ $post->title }} </h6>
                    <p> {{ $post->subtitle }} </p>
                </div>
            </small>
            <p>
                Postado em:
                <i class="fa fa-clock-o"
                   aria-hidden="true"></i> {{ $post->created_at->format('d/m/y') }}
                as {{ $post->created_at->format('H:i') }}
            </p>

            @if(Request::is('home'))
                <a href="{{ url('blog/exclusivo/' . $post->id) }}" class="read_more"><p> Ler mais <i
                                class="fa fa-long-arrow-right" aria-hidden="true"></i></p></a>
            @else
                <a href="{{ url('post/' . $post->id) }}" class="read_more"><p> Ler mais <i
                                class="fa fa-long-arrow-right" aria-hidden="true"></i></p></a>
            @endif


        </div>
    </article>

    {{--
    <article class="our_blog">
        <div class="blog_image">
            <img src="{{ asset( $post->image_url ) }}" alt="image">
        </div>

        <div class="blog_detail">
            <div class="category_heading">
                <a href="#"> <h6> {{ $post->title }} </h6> </a>
                <a href="#"> <h5> {{ $post->subtitle }} </h5> </a>

                <ul>
                    <li> <i class="fa fa-clock-o" aria-hidden="true"></i> {{ $post->created_at }} </li>
                    <!--<li> <a href="#"> <i class="fa fa-comments-o" aria-hidden="true"></i> Comments </a> </li>-->
                </ul>

                <a href="{{ url('post/' . $post->id) }}" class="read_more"> <p> Ler mais <i class="fa fa-long-arrow-right" aria-hidden="true"></i> </p> </a>
            </div>
        </div>
    </article>
    --}}
</div>

resources/views/parts/comments_post.blade.php
<div class="col-md-12">

    <div class="">

        <div class="well">
            <h4>Deixe um comentário:</h4>

            {!! BootForm::open()->action(route('comentario.store')) !!}

            {!! BootForm::hidden('post_id')->value($post->id) !!}
            {!! BootForm::text('Título do comentário', 'title')->placeholder('Escreva algo caso deseje dar uma descrição do seu comentário') !!}
            {!! BootForm::textarea('Escreva o comentário', 'comment')->required()->rows(3) !!}

            {!! BootForm::submit('Postar comentário')->addClass('btn btn-primary') !!}

            {!! BootForm::close() !!}

        </div>

        <h4> Comentários </h4>

        @include('page.comments')

    </div>
</div>